### ISSUE TITLE
[enhancement] error log in browser on empty submit 

### ISSUE THREAD

**Issue by VibhorCodecianGupta** [coding-blocks/boss#103]
![screen shot 2018-05-27 at 8 41 22 pm](https://user-images.githubusercontent.com/29275810/40587568-834e5de6-61ee-11e8-9ef6-6826d60f90e4.png)

This window shows up when you hit submit button on the 'add claims' page without filling in any details.
This should probably occur as a flash message rather than the entire log.

Work in progress.

**Comment by Dhroov7** [comment]
@championswimmer Done! PR #110
