### ISSUE TITLE
Stats show 'NaN' if the figure is zero

### ISSUE THREAD

**Issue by VibhorCodecianGupta** [coding-blocks/boss#108]
![screen shot 2018-05-28 at 10 46 11 pm](https://user-images.githubusercontent.com/29275810/40624245-12038356-62c9-11e8-886b-b097e0087d84.png)

This should just show 0, instead of 'Nan 0'.

**Comment by VibhorCodecianGupta** [comment]
Done, #109

**Comment by ananay** [comment]
Done here #111

**Comment by VibhorCodecianGupta** [comment]
@championswimmer the issue i was pointing out that day in #109 was this:

using `isNaN(x)` leads to type conversion. Which somehow always makes the value inside `NaN` and hence variables are always being set to 0. Relevant screenshots follow. I logged the types of the variables before and after the `isNaN(x)` check, and you can see the conversion from object to number.

![screen shot 2018-06-01 at 5 10 59 am](https://user-images.githubusercontent.com/29275810/40813971-34468f64-655b-11e8-8a23-a2a9f364635c.png)

![screen shot 2018-06-01 at 5 11 09 am](https://user-images.githubusercontent.com/29275810/40813961-279e7600-655b-11e8-9619-e22dc365a760.png)

using `Number.isNaN(x)` does not lead to such type conversions, as evident in the screenshots. Hence an `NaN` value is correctly identified if present, and is set to 0 only if it actually is `NaN`. Relevant screenshots

![screen shot 2018-06-01 at 5 12 32 am](https://user-images.githubusercontent.com/29275810/40813996-65e717a0-655b-11e8-9e35-706b5524715d.png)

![screen shot 2018-06-01 at 5 12 23 am](https://user-images.githubusercontent.com/29275810/40814002-7046eaf4-655b-11e8-9eab-f22ce3e6846a.png)


The non zero figure in the accepted bounty was achieved by granting myself admin access and hence accepting the bounties I myself claimed.

**Comment by championswimmer** [comment]
Ok this seems correct.  

Your PR had  !isNaN which definitely gave wrong results when I checked

**Comment by VibhorCodecianGupta** [comment]
Great. Then should I update the PR and use `Number.isNaN(x)` instead? That definitely gives correct results.

**Comment by championswimmer** [comment]
The great thing about booleans is there are only 2 values. So if something doesn't work, you can simply prepend with `!`

**Comment by championswimmer** [comment]
I'll suggest make a fresh PR with `Number.isNaN` on top of current head of project

**Comment by championswimmer** [comment]
someone from the team fixed while deploying.

**Comment by VibhorCodecianGupta** [comment]
Yes I just noticed. Nice!
