### ISSUE TITLE
Open Issues Showing 404 error

### ISSUE THREAD

**Issue by AmanGarg97** [coding-blocks/boss#140]
![screenshot 403](https://user-images.githubusercontent.com/31107917/41519556-6c6e4088-72e6-11e8-9e02-4549887a4fb0.png)

**Clicking on Open Issues is showing 404 error when the user is not logged in Github.**

**Comment by aggarwalpulkit596** [comment]
This is not an issue of boss first of all and secondly is not an issue at all .

**Comment by championswimmer** [comment]
you need to be logged in to see
