### ISSUE TITLE
also add filter by bounty amount

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/boss#142]
**NOTE This will be 1000 bounty points if it uses a range slider (like max, min price sliders on ecommerce websites). It will be 200 points if it is done via dropdown**

**Comment by prankshaw** [comment]
is this issue open or not, because I think #143 does this, if not, I will like to be assigned to this issue

**Comment by Dhroov7** [comment]
@championswimmer PR #144

**Comment by championswimmer** [comment]
archit's implementation was the best
