### ISSUE TITLE
add logic to disable POST /claims/ from 16th August 00:00 am 

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/boss#156]

**Comment by VibhorCodecianGupta** [comment]
#158

**Comment by firefinchdev** [comment]
Done #159 
@championswimmer 
Commited earlier.
Pls Review

**Comment by championswimmer** [comment]
my fellow countrymen, Indian Standard Time please

**Comment by VibhorCodecianGupta** [comment]
@championswimmer done #158 with IST

**Comment by firefinchdev** [comment]
@championswimmer 
Already Done #159

**Comment by championswimmer** [comment]
@firefinchdev had pushed the fix earlier
