### ISSUE TITLE
BOSS Winners Contact Information

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/boss#165]
Can the winners please email me their phoneNo, email addr, college name, branch, year of graduation to arnav [at] codingblocks [dot] com ASAP

@firefinchdev
@aggarwalpulkit596
@architkshk
@VibhorCodecianGupta
@kapillamba4
@Dhroov7 
@lazy-god 
@bhavyaagg
@Rishabh570 
@venomousboxer

**Comment by championswimmer** [comment]
Write a comment here once you've already sent it. Will close issue once I get all 10

**Comment by architkshk** [comment]
Sent @championswimmer

**Comment by VibhorCodecianGupta** [comment]
Sent @championswimmer

**Comment by kapillamba4** [comment]
Sent @championswimmer

**Comment by aggarwalpulkit596** [comment]
sent @championswimmer

**Comment by lazy-god** [comment]
sent @championswimmer

**Comment by venomousboxer** [comment]
sent @championswimmer

**Comment by firefinchdev** [comment]
sent @championswimmer

**Comment by Rishabh570** [comment]
sent @championswimmer

**Comment by Dhroov7** [comment]
@championswimmer sent.
