### ISSUE TITLE
Adding a delete button with all the claimed records

### ISSUE THREAD

**Issue by muskankhedia** [coding-blocks/boss#181]
A delete button to be added with every claimed record in the boss bounty points claimed page so that a participant can delete a record if added mistakenly or had made some mistake.

**Comment by muskankhedia** [comment]
@witty123 can I work on this ?

**Comment by abhishek97** [comment]
There is already an issue here: https://github.com/coding-blocks/boss/issues/152

**Comment by muskankhedia** [comment]
ohh.. i didnot see that. Thank u
