### ISSUE TITLE
Gitter redirect to 2020 lobby

### ISSUE THREAD

**Issue by praj1wal** [coding-blocks/boss#197]
Currently the gitter option is redirected to the 2019 boss lobby. It needs to be redirected to 2020 boss lobby.

**Comment by praj1wal** [comment]
@championswimmer  any bounties for this?

**Comment by abhishek97** [comment]
Yes, you can claim 20 for raising an accepted issue.

**Comment by HashTalmiz** [comment]
PR with change: https://github.com/coding-blocks/boss/pull/230
