### ISSUE TITLE
Filters should be at the centre of the screen

### ISSUE THREAD

**Issue by samagragupta** [coding-blocks/boss#202]
![Capture](https://user-images.githubusercontent.com/32234926/82052075-a8f5ba00-96d8-11ea-9a81-70914e274652.JPG)
In mobile view: Filters should be at the centre of the screen

**Comment by samagragupta** [comment]
@abhishek97 Can you please add bounty?

**Comment by samagragupta** [comment]
@hereisnaman @abhishek97 Can you please add bounty?

**Comment by aannaassalam** [comment]
Please close this issue @hereisnaman

**Comment by aannaassalam** [comment]
Please close this issue @hereisnaman
