### ISSUE TITLE
Header is not visible properly for smaller window size

### ISSUE THREAD

**Issue by samagragupta** [coding-blocks/boss#206]
![Capture](https://user-images.githubusercontent.com/32234926/82058249-1d812680-96e2-11ea-8448-58b7e93d2b9a.JPG)

**Comment by samagragupta** [comment]
@hereisnaman @abhishek97 Can you please add bounty?

**Comment by aannaassalam** [comment]
Can you please elaborate your issue??

**Comment by aannaassalam** [comment]
Why have you closed this issue
