### ISSUE TITLE
Increase the timings of login token to expire as it logs out the user in very few minutes.

### ISSUE THREAD

**Issue by hardik0899** [coding-blocks/boss#213]

**Comment by hardik0899** [comment]
@hereisnaman bro is this not an issue?

**Comment by hereisnaman** [comment]
@hardik0899 you can claim 20 points for raising this issue. 

Closing this in favor of https://github.com/coding-blocks/boss/issues/218

**Comment by hardik0899** [comment]
> @hardik0899 you can claim 20 points for raising this issue.
> 
> Closing this in favor of #218

Ok thanks for the info @hereisnaman bhaiyia
