### ISSUE TITLE
boss mobile view of navbar is not responsive 

### ISSUE THREAD

**Issue by Mayank4git** [coding-blocks/boss#214]
when we open navbar of boss website in mobile then text overlay on background text.It is not working properly.Mobile responsiveness is not working on mobile of boss website.

![new3](https://user-images.githubusercontent.com/26319657/82078515-d6edf500-96fe-11ea-8903-9999dc0ff9e3.jpg)

**device used**
**mi A3**

**Comment by Mayank4git** [comment]
can there be bounty for this?

**Comment by hereisnaman** [comment]
Assigned Bounty.

**Comment by amzamani** [comment]
Please assign this to me.

**Comment by Mayank4git** [comment]
@hereisnaman thanks :) to assign bounty to my issue

**Comment by jugshaurya** [comment]
can anyone work on this issue or have to wait for the assignment?

**Comment by Mayank4git** [comment]
Yes I have almost complete it.

**Comment by Mayank4git** [comment]
@jugshaurya i will pull request on this after one hour.work is almost completed

**Comment by jugshaurya** [comment]
ok @Mayank4git let me know if i can help

**Comment by Mayank4git** [comment]
Definitely
