### ISSUE TITLE
Transparent taskbar, text overlaps on scrolling

### ISSUE THREAD

**Issue by Adarsh08X** [coding-blocks/boss#217]
Background of taskbar is transparent resulting in overlapping of text upon scrolling i would like to solve the issue

<img width="960" alt="2020-05-15 (1)" src="https://user-images.githubusercontent.com/51786499/82083185-ec671d00-9706-11ea-9515-84de6a26d195.png">

**Comment by hereisnaman** [comment]
Assigned bounty.

**Comment by iemprashant** [comment]
Sir, which repo if of boss frontend I am unable to find

**Comment by shivam-bit** [comment]
i would like to work on this please assign

**Comment by hereisnaman** [comment]
> Sir, which repo if of boss frontend I am unable to find

This is a server side rendered project. There is no separate frontend.

**Comment by iemprashant** [comment]
> > Sir, which repo if of boss frontend I am unable to find
> 
> This is a server side rendered project. There is no separate frontend.

Thanks bhaiya , I didn't know about that earlier

**Comment by amzamani** [comment]
Bug resolved
Created a pull request :
https://github.com/coding-blocks/boss/pull/225

Now the taskbar text does not overlaps on scrolling.
![Screenshot 2020-05-16 at 2 39 26 AM](https://user-images.githubusercontent.com/62957837/82097039-be420700-971f-11ea-8ff7-df467735ce2c.png)

**Comment by aannaassalam** [comment]
@abhishek97 please go through the pr's and assign bounties to one whom you feel is best
