### ISSUE TITLE
Automatic Logout after 7-8 mins

### ISSUE THREAD

**Issue by mnb27** [coding-blocks/boss#218]
https://boss.codingblocks.com/
Requires Login again and again in duration of 7- 8 minutes.
Timeout time to be updated.
![Screenshot from 2020-05-16 12-43-06](https://user-images.githubusercontent.com/52792904/82113389-4bfb1200-9773-11ea-81f8-778c3b418a0b.png)

**Comment by mnb27** [comment]
@abhishek97 Please assign bounties so that I can work on the issue.

**Comment by iemprashant** [comment]
@abhishek97  please check 
Increase the timings of the login token to expire as it logs out the user in very few minutes. #213
both are same
