### ISSUE TITLE
add a script to run migrations

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/boss#22]
- migrations are in `/db/migrations/<old-version>-to-<new-version>.sql` 
 - add a script called `migratedb` (use node itself, or shell - whatever you prefer, do not write in python/ruby or anything that is not required to run the rest of the project)
- pickup db name user pass etc from secrets.json (example format is secrets-sample.json) 

 -  [ ] running `migratedb --from 0.0.1 --to 0.0.3` should run all migrations like 001-to-002 and 002-to-003
- [ ] just running `migratedb` should open interactive mode. chose which migration to run from a list of migrations.

- [ ] if there are any DELETE/DROP commands in migrations, confirm with Y/N prompt in shell before executing that line

**Comment by abhishek97** [comment]
@championswimmer  Each migration is to be run in a transaction right?

**Comment by championswimmer** [comment]
@abhishek97 wrote it ? 
you can take pointers from this one https://github.com/coding-blocks/oneauth/blob/master/scripts/migrate.js

**Comment by shreyateeza** [comment]
I am working on this issue.
