### ISSUE TITLE
Generate Modal popup of login when visiting Boss site

### ISSUE THREAD

**Issue by iemprashant** [coding-blocks/boss#220]
As we open site it would be great to get a  popup to log in for contribution as we have to log in for claims so it will be great for user experience

**Comment by abhishek97** [comment]
@iemprashant There are BOSS features which don't require login, For ex: just viewing the leaderboard and claims. It'll be bad UX to require login for these basic public actions.

**Comment by iemprashant** [comment]
When we click on a claim button we can then go for login popup as if we have not logged in then have to go to the login button and adding credentials. So if it automatically popup it will definitely be addon in UX
