### ISSUE TITLE
Overlapping of text in the navbar due to scrolling.

### ISSUE THREAD

**Issue by Daggerhub** [coding-blocks/boss#226]
![Screenshot (8)](https://user-images.githubusercontent.com/52444845/82109577-c8cac380-9754-11ea-87d3-2e070f0d0fa2.png)

**Comment by Daggerhub** [comment]
This can be overcome if during scrolling the navbar has a darker color.

**Comment by iemprashant** [comment]
please check issue #200 and #201 already mentioned there
