### ISSUE TITLE
Bug: Gitter button redirects to 2019 BOSS gitter

### ISSUE THREAD

**Issue by jashasweejena** [coding-blocks/boss#227]
The Gitter button on the toolbar below redirects to the BOSS 2019 Gitter chat. Redirect it to BOSS 2020 instead

![image](https://user-images.githubusercontent.com/20218197/82112055-3122a080-9767-11ea-90a0-acb9ccc4d3a7.png)

**Comment by iemprashant** [comment]
I think it is just a 2019 lobby but this time they are using discord

**Comment by mnb27** [comment]
@jashasweejena  Already mentioned this issue.
 #215

**Comment by abhishek97** [comment]
https://github.com/coding-blocks/boss/issues/197
