### ISSUE TITLE
Gitter to Discord (change in nav link)

### ISSUE THREAD

**Issue by HashTalmiz** [coding-blocks/boss#229]
The navigation page has *Gitter* as its link for discussions. Since discussions have moved over to **Discord** the link needs to be changed with the associated icon.
@hereisnaman  Please assign BOUNTY :D

**Comment by HashTalmiz** [comment]
Also, I've made the changes in the PR here: https://github.com/coding-blocks/boss/pull/230
@hereisnaman have a look, its ready for merge

**Comment by abhishek97** [comment]
Duplicate of https://github.com/coding-blocks/boss/issues/197
