### ISSUE TITLE
Undocumentaed Secret in secrets.json

### ISSUE THREAD

**Issue by YashKumarVerma** [coding-blocks/boss#241]
There is no mention about  this secret in the readme, which is confusing while setting up local dev environment.

```json
"secret" : "someMuchSecretFFS"
```

**Comment by sahuaman83** [comment]
can i work on this issue..i can fix this

**Comment by YashKumarVerma** [comment]
> can i work on this issue..i can fix this

which token is this actually?

**Comment by sahuaman83** [comment]
actually, according to readme it also suggests to rename this file and add your details, but if person rename this secrets-sample.json file to secrets.json they  overwrite secrets-sample.json file which will be making errors while setting up dev environment

**Comment by YashKumarVerma** [comment]
> actually, according to readme it also suggests to rename this file and add your details, but if person rename this secrets-sample.json file to secrets.json they overwrite secrets-sample.json file which will be making errors while setting up dev environment

I think the readme is verbose about using the secrets, but my point here is that there is no mention (if i looked it right) about the first **secret**. from where to obtain it, which api.

I hope I'm not confusing to understand

**Comment by hereisnaman** [comment]
The secret can be anything, it is used to generate sessions keys. Closing this issue.
