### ISSUE TITLE
Gitter icon is redirecting to Gitter's old lobby boss-2019

### ISSUE THREAD

**Issue by aannaassalam** [coding-blocks/boss#248]
The Gitter block on BOSS website is redirecting to users to boss-2019-lobby. 
It must redirect users to the new lobby of boss 2020

**Comment by aannaassalam** [comment]
@abhishek97 please assign bounties to it so that I can start working on it...

**Comment by mnb27** [comment]
@aannaassalam @abhishek97  I had mentioned this issue before this. #215 
Please assign bounties to older raised issues first.

**Comment by aannaassalam** [comment]
@mnb27 you didn't requested them to assign bounties but I did and after the assignment of bounties I had given the solution
The issue firstly must be reviewed by a contributor and then only and bounties can be assigned and PR can be made to claim that

**Comment by mnb27** [comment]
@aannaassalam  We don't have to request to assign bounties.

**Comment by aannaassalam** [comment]
@mnb27 ooh thank you for this piece of information
It was like I didn't knew that before

**Comment by abhishek97** [comment]
Duplicate of https://github.com/coding-blocks/boss/issues/197
