### ISSUE TITLE
Show Rank and "Your Rank" on leaderboard

### ISSUE THREAD

**Issue by ankiiitraj** [coding-blocks/boss#251]
- [x] Show Ranks on leaderboard.
- [x] If user is logged in show "Your Rank" on top of leaderboard and then the reset of the leaderboard. Similar to the leaderboard shown on [Hackerblocks](https://hack.codingblocks.com/app/)

**Comment by ankiiitraj** [comment]
Hi @championswimmer , Please have a look here. 
If this is okay to you assign the bounty. Thanks.

**Comment by jugshaurya** [comment]
@ankiiitraj are you working on it?

**Comment by ankiiitraj** [comment]
@jugshaurya I am working on it.

**Comment by ankiiitraj** [comment]
Hi @abhishek97 Kindly assign this to me

**Comment by jugshaurya** [comment]
ok @ankiiitraj

**Comment by hereisnaman** [comment]
Rather than showing the rank separately, if the user stats are not already in the table, add a row at the top in the table with the user's rank and other stats. Highlight the row for the logged in user stat using different bg.

**Comment by ankiiitraj** [comment]
> Rather than showing the rank separately, if the user stats are not already in the table, add a row at the top in the table with the user's rank and other stats. Highlight the row for the logged in user stat using different bg.

Working on further improvement regarding this suggestion

**Comment by ankiiitraj** [comment]
Hi @hereisnaman - Apologies for late PR as I was figuring out things as I am new to ember and sequalize.
Here are the screenshots
Not logged in
![Screenshot from 2020-05-19 13-05-28](https://user-images.githubusercontent.com/48787278/82299695-75b27400-99d3-11ea-9eba-615a00a6160e.png)
Logged In
![Screenshot from 2020-05-19 13-10-03](https://user-images.githubusercontent.com/48787278/82299972-d6da4780-99d3-11ea-8b0d-6736474734e3.png)
