### ISSUE TITLE
handle admin levels here too

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/boss#257]
we take admin or not value from oneauth

but we need a way to manage admin flag on users here at boss as well. so someone who is not admin on oneauth can be marked as admin here too.

**Comment by championswimmer** [comment]
BOUNTY = 300

**Comment by YashKumarVerma** [comment]
@championswimmer  how should this be implemented ? should we add a feature for other user who is already logged as admin to make other "users" as admin ?

**Comment by championswimmer** [comment]
Yes existing admins can make others admin

**Comment by YashKumarVerma** [comment]
sure, will be sending pr for it.

---

**Comment by prathambatra** [comment]
@championswimmer I am working on this.  I have a doubt. right now there is only oneauthid stored in users table. So admin can only see or make admin based on oneauthid. is it fine? or do want u want to make or see admin by username also. so I will write a migration

**Comment by championswimmer** [comment]
Just based on oneauth id is fine.
