### ISSUE TITLE
Add conflicting claims section on accept claims page

### ISSUE THREAD

**Issue by hereisnaman** [coding-blocks/boss#260]
Based on the issue and pull request url, find the list of conflicting claims and display them on the accept claims page.

Solutions with better layout, and covering all the edge cases will be preferred.

Things to take care of:
1. If the target claim is for a pull request (i.e the pull request url point to a pr on github and not an issue), then only find conflicting claims which are also for a PR only. Some claims are added for suggesting features/issues, in that case the the pull request url point to an issue on github.
2. There can be terminating '/' in some urls and not others. Can be similar cases for 'http' and 'https'. Use the `like` sql operator to make db queries where ever required to cover such cases.

This issue has 700 bounty points.

![Screenshot 2020-05-17 at 8 36 55 PM](https://user-images.githubusercontent.com/22571395/82152716-db421b80-9880-11ea-8ed9-590810367139.png)

**Comment by YashKumarVerma** [comment]
I would like to work on it once https://github.com/coding-blocks/boss/issues/241 is cleared out, as it stops from setting up a local dev environment

**Comment by prathambatra** [comment]
@hereisnaman can I work on this?

**Comment by hereisnaman** [comment]
> @hereisnaman can I work on this?

why not

**Comment by prathambatra** [comment]
![Screenshot from 2020-05-19 01-23-11](https://user-images.githubusercontent.com/29707062/82253909-83361280-996f-11ea-9f4a-4ce03a5b216d.png)
@hereisnaman I am facing this issue. please help

**Comment by YashKumarVerma** [comment]
> @hereisnaman can I work on this?

There's an active pr going for this : #279

**Comment by hereisnaman** [comment]
> > @hereisnaman can I work on this?
> 
> There's an active pr going for this : #279

Leave it for me to decide which PR to merge.

The PRs are merged based on code quality and best solutions. Until there is already a good enough solution, anyone can work on it.
