### ISSUE TITLE
Footer is not proper

### ISSUE THREAD

**Issue by samagragupta** [coding-blocks/boss#270]
![Capture](https://user-images.githubusercontent.com/32234926/82172939-5b9c6700-98e9-11ea-80c5-a4d7175beaaf.JPG)

**Comment by samagragupta** [comment]
@abhishek97 Can you please add bounty?

**Comment by YashKumarVerma** [comment]
@samagragupta  please send a pr, the bounty can be added later on also, this issue is making the site unusable. :cry:

**Comment by samagragupta** [comment]
@YashKumarVerma Sure

**Comment by ankiiitraj** [comment]
Hi mentors @hereisnaman please assign the bounty her. Thanks!

**Comment by hereisnaman** [comment]
footer has been removed
