### ISSUE TITLE
Error 500 in /leaderboard route 

### ISSUE THREAD

**Issue by YashKumarVerma** [coding-blocks/boss#272]
The route throws 500 error when:

- a noninteger year passed into URL
- a year passed for which entries don't exist for boss (for example 2050)

---

Working on it

**Comment by prabalsingh24** [comment]
This don't look like a bug to me. If url is incorrect, it should throw error. 400 (bad request) error instead of 500 maybe?
@hereisnaman will have to confirm though :)

**Comment by hereisnaman** [comment]
@YashKumarVerma @prabalsingh24 Its a bug, it should return 404 page. Good find.
