### ISSUE TITLE
Don't allow duplicate claims

### ISSUE THREAD

**Issue by prabalsingh24** [coding-blocks/boss#275]
Kind of an extension of #260 

There might be cases when a student add a same claim twice. And if the mentor accepts the both of them, it will give student double bounty. There should be feature to avoid having duplicate claims 

@hereisnaman This can be a different issue right? Because this feature is slightly different than conflicting claims one

**Comment by ankiiitraj** [comment]
Hi @prabalsingh24 , sometimes mentors allow both the persons who made PR for the same isuue to claim points. So I think there can be another solution for this.

**Comment by prabalsingh24** [comment]
No that is a conflicting issue (Both of them have same issue but different PRs) . I am talking about duplicates (Same username, same issue, same pr)

**Comment by prabalsingh24** [comment]
Edit: This is a already a feature. but It is not working for the cases when different type of URL is used (`/` in the end, `http-->https`),

**Comment by ankiiitraj** [comment]
Gotcha @prabalsingh24

**Comment by hereisnaman** [comment]
You can work on it.

**Comment by ankiiitraj** [comment]
This work feature is already present. I tried adding two claims with same pull url and I got error page saying I have taken that already.

**Comment by prabalsingh24** [comment]
> This work feature is already present. I tried adding two claims with same pull url and I got error page saying I have taken that already.
Check my previous comment
https://github.com/coding-blocks/boss/issues/275#issuecomment-630006939
