### ISSUE TITLE
Footer too large

### ISSUE THREAD

**Issue by Sapna2001** [coding-blocks/boss#283]
The footer is too large and due to this, the users are not able to access the whole content on the page.
![Annotation 2020-05-18 161052](https://user-images.githubusercontent.com/56690856/82204359-5f001480-9922-11ea-8b33-3c8149f4d5dc.png)

**Comment by prabalsingh24** [comment]
Duplicate of https://github.com/coding-blocks/boss/issues/270

**Comment by hereisnaman** [comment]
footer has been removed
