### ISSUE TITLE
Navbar Transparent Issue 

### ISSUE THREAD

**Issue by Keshavcool** [coding-blocks/boss#286]
![Screenshot_20200516-073643](https://user-images.githubusercontent.com/40866592/82218082-f53f3500-9938-11ea-9d37-5f73034f0465.jpg)

When navbar is open it is not backed up by some backdrop or background means it open as transparent over the content.

**Comment by hereisnaman** [comment]
Closing this in favor of https://github.com/coding-blocks/boss/issues/214
