### ISSUE TITLE
use cb bootstrap theme

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/boss#287]
- semantic ui isn't well maintained anymore (fomantic exists, but nevertheless)
- we have our own branded bootstrap edition - https://bootstrap.codingblocks.in

we will move the entire frontend (i.e. hbs pages) to cb's bootstrap and remove all semantic/fomantic stuff

**Comment by prathambatra** [comment]
I would like to work on this

**Comment by YashKumarVerma** [comment]
Interested in working on this

**Comment by samagragupta** [comment]
@championswimmer Can we not divide it into parts?

**Comment by championswimmer** [comment]
How? A css framework switch will have to be in one go. It's only 3-4 views.
