### ISSUE TITLE
Pagination out of screen

### ISSUE THREAD

**Issue by samagragupta** [coding-blocks/boss#309]
![Capture](https://user-images.githubusercontent.com/32234926/82285470-28290d80-99b9-11ea-8444-4c32330ea048.JPG)

**Comment by samagragupta** [comment]
@hereisnaman Should we decrease the pagination size>

**Comment by ankiiitraj** [comment]
We can make this maybe like 1, 2, 3, . . . , 10, 11

**Comment by samagragupta** [comment]
@ankiiitraj This will increase the width of the page. More than the current wodth

**Comment by ankiiitraj** [comment]
I am talking about doing something like this . . .
![Screenshot from 2020-05-19 16-30-48](https://user-images.githubusercontent.com/48787278/82318815-1e6dcd00-99ee-11ea-93e1-4d0bb787966a.png)

**Comment by samagragupta** [comment]
Let @hereisnaman decide.

**Comment by YashKumarVerma** [comment]
Is someone sending PR ?

**Comment by ankiiitraj** [comment]
I would like to make the PR after reaching to conclusion

**Comment by samagragupta** [comment]
I am already making a PR, so please do not make spam with PRs on a single issue.

**Comment by hereisnaman** [comment]
> I am talking about doing something like this . . .
> ![Screenshot from 2020-05-19 16-30-48](https://user-images.githubusercontent.com/48787278/82318815-1e6dcd00-99ee-11ea-93e1-4d0bb787966a.png)

This is a good idea. @ankiiitraj @samagragupta , @YashKumarVerma you all can work on this. Best code quality and logic will be selected.

**Comment by YashKumarVerma** [comment]
@hereisnaman,
should I claim the bounty for this one as well as this was fixed under https://github.com/coding-blocks/boss/pull/331 ?
