### ISSUE TITLE
Don't allow same links for  "issue" and "pull" in add bounty section

### ISSUE THREAD

**Issue by pulkitmittal19** [coding-blocks/boss#311]
Many of them are putting **same links** for **pull request** and **issue** to claim their **bounty** which **shouldn't** be allowed and **rejected automatically**

![issue_10](https://user-images.githubusercontent.com/53789333/82287195-41cc5400-99bd-11ea-8b69-7cd245735305.png)

![issue_9](https://user-images.githubusercontent.com/53789333/82287198-442eae00-99bd-11ea-982d-10be71f0ddd8.png)

![issue_8](https://user-images.githubusercontent.com/53789333/82287201-44c74480-99bd-11ea-8e47-f47d0e2d312e.png)

**Comment by prabalsingh24** [comment]
This is not a bug. If you create an issue you'll be getting 20 bounties. So when issueUrl and pullUrl are same, it because they're claiming bounty for creating an issue :)
