### ISSUE TITLE
[Open for suggestions] On npm start files appear to be commited

### ISSUE THREAD

**Issue by ankiiitraj** [coding-blocks/boss#313]
Steps to reproduce :
1. Execute npm start
After install this happens
![Screenshot from 2020-05-19 13-54-52](https://user-images.githubusercontent.com/48787278/82303254-54a05200-99d8-11ea-8240-626775ac8932.png)
Possible solution:
Adding these files one by one to .gitignore
***Open for solution suggestion***

**Comment by prathambatra** [comment]
@hereisnaman please have a look.

**Comment by hereisnaman** [comment]
Add public_static to gitignore
