### ISSUE TITLE
On scrolling table of leader board and claim overlaps with header

### ISSUE THREAD

**Issue by mdazmat9** [coding-blocks/boss#323]
![image](https://user-images.githubusercontent.com/38210242/82365918-fce10580-9a2e-11ea-9ab5-0496df36112f.png)

**Comment by mdazmat9** [comment]
@hereisnaman  please check if its a bug

**Comment by ankiiitraj** [comment]
Duplicate issue https://github.com/coding-blocks/boss/issues/217
Please close this
