### ISSUE TITLE
Improve pagination of Leaderboard.

### ISSUE THREAD

**Issue by ankiiitraj** [coding-blocks/boss#326]
Like that of issue #309  .
Leader board can also go out of page.

**Comment by YashKumarVerma** [comment]
appreciating your work, please try doing it in bootstrap as entire system is being shifted to bootstrap.

**Comment by ankiiitraj** [comment]
Hi actually I have just pushed it. So maybe after this one I would definitely keep that in mind

**Comment by ankiiitraj** [comment]
Hi @hereisnaman Kindly add the bounty label. Thanks
