### ISSUE TITLE
[Suggestion needed] Only on pull merge, allow email notification of BOSS-Bot comment

### ISSUE THREAD

**Issue by ankiiitraj** [coding-blocks/boss#332]
Currently for all the new issue or pull request created by the user Bot comment notification is sent through email which is kind of annoying and irrelevant.
Whereas, email notification of Bot comment for pull request merge can be useful.

Solution suggested:
Maybe not tagging the user with '@' can solve the problem
**Open for suggestion**
P.S. I want to work on this

**Comment by prabalsingh24** [comment]
The email thing is a github feature not the bot feature. Bot only comments when you open a pr/issue or when a pr is merged which I guess is fine

**Comment by ankiiitraj** [comment]
Gotcha @prabalsingh24 
Closing
