### ISSUE TITLE
New added feature of Hover Effects doesn't work on leaderboard and claim options

### ISSUE THREAD

**Issue by aannaassalam** [coding-blocks/boss#343]
The brand new added hover effects on boss open source code does not work on leaderboard and claim option while running it locally on our machine.
Secondly, on hovering only colors are changing, it would look great if the fonts enlarge a bit on hovering to give it a 3D effect and a bit of cool sweeping underline effect too.
It may give a whole new turn to the life of hovering in boss navbar.

1. Hover effects working on Leaderboard & Claim button too.
2. Bit of font enlargement on hovering.
3. Some cool swiping underline effect to make website much more responsive.

**Comment by aannaassalam** [comment]
@championswimmer @abhishek97 please assign bounties to it so that I can apply my PR for review

**Comment by aannaassalam** [comment]
@hereisnaman please assign bounties so that I ca  start working on this

**Comment by hereisnaman** [comment]
We do not need font enlargement in navbar on hover. Also the theme will be changed quite a bit as we are migrating to bootstrap. 

We can discuss this again after the migration is completed based on the then scenario. For now I am closing this.

**Comment by aannaassalam** [comment]
ok
