### ISSUE TITLE
On clicking Leaderboard on the boss website throws error

### ISSUE THREAD

**Issue by aannaassalam** [coding-blocks/boss#345]
![BOSS - Google Chrome 5_24_2020 2_22_01 AM](https://user-images.githubusercontent.com/54815094/82740335-895c3280-9d65-11ea-8b3c-24ec94a7c292.png)
 
This is the issue that its throwing and it needs a quick fix 
@hereisnaman please review this error and assign bounties to this issue so that I can start working on it

**Comment by aannaassalam** [comment]
@hereisnaman please assign my 20 Bounties for raising this issue 
I have ak

**Comment by aannaassalam** [comment]
I am not able to add a claim for 20 bounties for raising this issue

**Comment by prathambatra** [comment]
@hereisnaman this is happening because the valid URL is leaderboard/{year} . so you want a new view at /leaderboard to choose year?

**Comment by hereisnaman** [comment]
> I am not able to add a claim for 20 bounties for raising this issue

What is the issue?

**Comment by hereisnaman** [comment]
> @hereisnaman this is happening because the valid URL is leaderboard/{year} . so you want a new view at /leaderboard to choose year?

/leaderboard should render the view for the latest year.

**Comment by aannaassalam** [comment]
> > I am not able to add a claim for 20 bounties for raising this issue
> 
> What is the issue?

Its asking for the link of pull request 
Can you assign me bounties without a claim???

**Comment by hereisnaman** [comment]
> > > I am not able to add a claim for 20 bounties for raising this issue
> > 
> > 
> > What is the issue?
> 
> Its asking for the link of pull request
> Can you assign me bounties without a claim???

You can put the link of the issue there.

**Comment by aannaassalam** [comment]
> > > > I am not able to add a claim for 20 bounties for raising this issue
> > > 
> > > 
> > > What is the issue?
> > 
> > 
> > Its asking for the link of pull request
> > Can you assign me bounties without a claim???
> 
> You can put the link of the issue there.

Done

please review the PR's and merge the one that is appropriate

**Comment by hereisnaman** [comment]
@aannaassalam @prathambatra the solutions you both provided are wrong. 

Here: https://github.com/coding-blocks/boss/pull/347/files#diff-00735162fe7c86f7936aace9c14fc4e6R50 check if the year is undefined and render for 2020. 

Because you both tried I'll give 50 points each. Please one of you create a PR for the solution.

**Comment by aannaassalam** [comment]
> @aannaassalam @prathambatra the solutions you both provided are wrong.
> 
> Here: https://github.com/coding-blocks/boss/pull/347/files#diff-00735162fe7c86f7936aace9c14fc4e6R50 check if the year is undefined and render for 2020.
> 
> Because you both tried I'll give 50 points each. Please one of you create a PR for the solution.

Thank you for the points 
I will start working on it tomorrow

**Comment by prathambatra** [comment]
> @aannaassalam @prathambatra the solutions you both provided are wrong.
> 
> Here: https://github.com/coding-blocks/boss/pull/347/files#diff-00735162fe7c86f7936aace9c14fc4e6R50 check if the year is undefined and render for 2020.
> 
> Because you both tried I'll give 50 points each. Please one of you create a PR for the solution.

done. why 50-50 :(

**Comment by hereisnaman** [comment]
> > @aannaassalam @prathambatra the solutions you both provided are wrong.
> > Here: https://github.com/coding-blocks/boss/pull/347/files#diff-00735162fe7c86f7936aace9c14fc4e6R50 check if the year is undefined and render for 2020.
> > Because you both tried I'll give 50 points each. Please one of you create a PR for the solution.
> 
> done. why 50-50 :(

Both of you didn't provide the right solution. I am giving you point just because you tried.

Another option is, I fix it and none of you get any points.

**Comment by prathambatra** [comment]
> > > @aannaassalam @prathambatra the solutions you both provided are wrong.
> > > Here: https://github.com/coding-blocks/boss/pull/347/files#diff-00735162fe7c86f7936aace9c14fc4e6R50 check if the year is undefined and render for 2020.
> > > Because you both tried I'll give 50 points each. Please one of you create a PR for the solution.
> > 
> > 
> > done. why 50-50 :(
> 
> Both of you didn't provide the right solution. I am giving you point just because you tried.
> 
> Another option is, I fix it and none of you get any points.

okay i will claim 50 only ;)

**Comment by prathambatra** [comment]
> > > > @aannaassalam @prathambatra the solutions you both provided are wrong.
> > > > Here: https://github.com/coding-blocks/boss/pull/347/files#diff-00735162fe7c86f7936aace9c14fc4e6R50 check if the year is undefined and render for 2020.
> > > > Because you both tried I'll give 50 points each. Please one of you create a PR for the solution.
> > > 
> > > 
> > > done. why 50-50 :(
> > 
> > 
> > Both of you didn't provide the right solution. I am giving you point just because you tried.
> > Another option is, I fix it and none of you get any points.
> 
> okay i will claim 50 only ;)

merge my PR.

**Comment by hereisnaman** [comment]
> > > > > @aannaassalam @prathambatra the solutions you both provided are wrong.
> > > > > Here: https://github.com/coding-blocks/boss/pull/347/files#diff-00735162fe7c86f7936aace9c14fc4e6R50 check if the year is undefined and render for 2020.
> > > > > Because you both tried I'll give 50 points each. Please one of you create a PR for the solution.
> > > > 
> > > > 
> > > > done. why 50-50 :(
> > > 
> > > 
> > > Both of you didn't provide the right solution. I am giving you point just because you tried.
> > > Another option is, I fix it and none of you get any points.
> > 
> > 
> > okay i will claim 50 only ;)
> 
> merge my PR.

added comments.

**Comment by aannaassalam** [comment]
@hereisnaman will I get my 20 points for raising the issue
