### ISSUE TITLE
404 error on leaderboard link on main page

### ISSUE THREAD

**Issue by prateek2211** [coding-blocks/boss#348]
On clicking `this page` button on home page, it redirects to https://boss.codingblocks.com/leaderboard , which gives 404 error
![Screenshot from 2020-05-24 13-19-22](https://user-images.githubusercontent.com/42961174/82748615-344e0a00-9dc1-11ea-8200-34495e557513.png)

Working link for leaderboard is https://boss.codingblocks.com/leaderboard/2020

With ref to #49

**Comment by hereisnaman** [comment]
Thanks for reporting, fix have been merged already. We will do the fresh deployment soon.
