### ISSUE TITLE
post-bootstrap-issues: self user rank to be redone in new site

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/boss#352]

**Comment by YashKumarVerma** [comment]
The reference to this issue was done by mistake, I've force pushed with a new commit message, but for some reason 
![image](https://user-images.githubusercontent.com/14032427/83096049-5944c480-a0c2-11ea-888f-041ea9d955bd.png) is not disappearing. 

Apologies for the confusion.

**Comment by YashKumarVerma** [comment]
If possible, can you please guide a bit what exactly needs to be done here?

**Comment by championswimmer** [comment]
this has been already done actually via https://github.com/coding-blocks/boss/issues/353
