### ISSUE TITLE
Leaderboard Error 404!

### ISSUE THREAD

**Issue by mnb27** [coding-blocks/boss#365]
Only Top 10 are displayed in the leaderboard.
Furthur leaderboard pages not found.
Screencast:
![Screencast from Thursday 28 May 2020 12_49_04  IST](https://user-images.githubusercontent.com/52792904/83111309-067b0500-a0e2-11ea-9ff7-f1e4aaa6d04b.gif)

**Comment by prathambatra** [comment]
@mnb27 I think this is due to broken pagination links. That's already an issue.

**Comment by aannaassalam** [comment]
@abhishek97 duplicate issue please close this issue

**Comment by mnb27** [comment]
> @mnb27 I think this is due to broken pagination links. That's already an issue.

Ok!! closing this issue.
