### ISSUE TITLE
Improper highlight box

### ISSUE THREAD

**Issue by mnb27** [coding-blocks/boss#366]
Highlight box radius is inconsistent.
http://boss.codingblocks.com/claims/view

Screenshot:
![11](https://user-images.githubusercontent.com/52792904/83120734-0c2b1780-a0ef-11ea-9bd2-6cc80d760219.png)
![12](https://user-images.githubusercontent.com/52792904/83120739-0df4db00-a0ef-11ea-82af-261409f3f3a2.png)

**Comment by championswimmer** [comment]
probably not an issue on second thoughts. it is fine whatever is there right now
