### ISSUE TITLE
Project: [ Link ]

### ISSUE THREAD

**Issue by mnb27** [coding-blocks/boss#367]
Project link directs to https://github.com/coding-blocks/ instead of respective project repo.
Screencast:
![Screencast from Thursday 28 May 2020 02_30_20  IST](https://user-images.githubusercontent.com/52792904/83121708-4c3eca00-a0f0-11ea-9865-31d58c9908a2.gif)

![h](https://user-images.githubusercontent.com/52792904/83121943-945dec80-a0f0-11ea-94bd-daca9b3e49de.png)

**Comment by samagragupta** [comment]
@championswimmer Could you please add bounty to this.
