### ISSUE TITLE
Pull Request also opening issueUrl on claim/id and claim/view page

### ISSUE THREAD

**Issue by prathambatra** [coding-blocks/boss#368]

**Comment by prathambatra** [comment]
![Screenshot from 2020-05-28 16-34-49](https://user-images.githubusercontent.com/29707062/83133999-53220880-a101-11ea-83c5-0fb388469def.png)
![rsz_screenshot_from_2020-05-28_14-55-48](https://user-images.githubusercontent.com/29707062/83134037-63d27e80-a101-11ea-88d3-e559693a8816.png)

**Comment by championswimmer** [comment]
did it myself
