### ISSUE TITLE
Github Bot not greeting new PRs

### ISSUE THREAD

**Issue by YashKumarVerma** [coding-blocks/boss#380]
The bot is not sending a welcome message for the PR which it earlier used to do.

Code for it:
https://github.com/coding-blocks/boss/blob/68a64a8c54ac65665020186f496a2b25fde3f08c/bot/index.js#L26-L45

Earlier:
![image](https://user-images.githubusercontent.com/14032427/83184664-65269a00-a147-11ea-9784-261d2abeb719.png)

Now:
![image](https://user-images.githubusercontent.com/14032427/83184693-740d4c80-a147-11ea-8e23-297338876813.png)

**Comment by hereisnaman** [comment]
Good work.
