### ISSUE TITLE
Issue with leaderboard

### ISSUE THREAD

**Issue by aryan7778** [coding-blocks/boss#397]
After going to last page there is no way to go to previous pages.
![leaderboard](https://user-images.githubusercontent.com/36998845/83834945-27101400-a70d-11ea-9ac8-de02c07e13cd.jpeg)

**Comment by amit2699** [comment]
@hereisnaman , Can I take this problem to solve it

**Comment by amit2699** [comment]
Issue labeled #403

**Comment by gurrrung** [comment]
NOTE TO BOUNTY REVIEWER: the PR above resolves two bounty issues.
