### ISSUE TITLE
API throws an error when adding a claim without a PR URL

### ISSUE THREAD

**Issue by ananay** [coding-blocks/boss#56]
Claims need to be submitted for only opening issues as well. Since they do not include a PR URL, the application should allow the PR URL field to be left blank.

a) In the case of "/api/claims/add", the server throws an error (shown below)
b) In the case of "/claims/add", the request "freezes up", doesn't add the claim and then cloudflare sends the thing shown below

Request output for a)
![image](https://user-images.githubusercontent.com/5569219/40047961-925dc38e-584e-11e8-84b1-936aeaca0503.png)

Request output for b)
![image](https://user-images.githubusercontent.com/5569219/40048775-aed6a704-5850-11e8-8d3c-3cd39731d303.png)

Proposed solution: Add necessary validation to all the fields and make the PR request field optional.

Apparently, creating too many of these requests on "/claims/add" can be DoS primitive.

**Comment by ananay** [comment]
@championswimmer @the-dagger @prateek27

**Comment by championswimmer** [comment]
Why would there be a claim without a PR ?

**Comment by ananay** [comment]
@championswimmer 
According to this https://github.com/coding-blocks/boss/issues/49, there are points for submitting an issue / bug. In this case, we don't have a PR because this is just a filing of an issue so here it doesn't make sense to input anything into the PR field.

**Comment by championswimmer** [comment]
The newly created issue will be the PR in that case. Mentioned that on gitter and faq.
