### ISSUE TITLE
[Feature] Add "no records found" if there are no records

### ISSUE THREAD

**Issue by till-tomorrow** [coding-blocks/boss#60]
![norecordfoundmessagenotfound](https://user-images.githubusercontent.com/21954525/40067639-3b417420-5884-11e8-9148-a1a39d07d84b.JPG)

If there are no accepted or rejected PRs, then show a suitable message like "No Records Found!!"

In reference to issue #49 .

**Comment by VibhorCodecianGupta** [comment]
Done in #124

**Comment by Dhroov7** [comment]
@championswimmer Done! PR #126
