### ISSUE TITLE
add sort by project name (in issue url)

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/boss#71]
Keeping this open you can add either 

 - filter by project
 - a search box where we can search project name

You can make it on frontend as a live filter, or make make the search as a rest query and make the backend send fresh list of claims which fulfill the search param

**Comment by aditigupta17** [comment]
I am working on this :+1:

**Comment by architkshk** [comment]
Hey @championswimmer,
What do you mean by issue url, a page for open issues? or is it view claim page?

**Comment by Nshul** [comment]
I would like to work on this.
