### ISSUE TITLE
stats page

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/boss#72]
create a page called 'stats' that shows

 - total bounties claimed
 - total bounties accepted
 - total no of claims filed
 - total no of participants (anyone who has 1 claim, irrespective of accepted is participant) 

_total bounties means sum of bounty points_ 

we are using semantic-ui so read up semantic docs, and make cards for each stat and make a nice UI for the page (not just a boring table 😆 )

**Comment by ananay** [comment]
Done! #73
