### ISSUE TITLE
Validate Github username when adding claim

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/boss#9]
The github username accepts anything  as of now. It should use github api to check if a username exits or not.

**Comment by championswimmer** [comment]
accepted. bounty added

**Comment by ArushiSinghal** [comment]
@championswimmer Is this issue solved? If yes, then please close it.

**Comment by shreyateeza** [comment]
@abhishek97 @championswimmer This issue needs to be closed as it is resolved.
