### ISSUE TITLE
Add a readme on how to set up this project and contribute

### ISSUE THREAD

**Issue by Nshul** [coding-blocks/boss#92]
While i was trying to resolve an issue, I found that there are no proper Getting Started instructions to begin working on this project.
I had to personally set up the database using PostgreSQL. (There is no mention in the Readme.md of this project like there is in the shortlr project)
I had to hardcode a workaround the required oneauth authorisation because if you attempt to authorise the localhost then callback URL doesn't match
If you are working on issue related to claims, then claims are added wrt the username of the github handle used in oneauth, so basically hardcode that too..

I don't know if there was any other proper method to start on the project. Any suggestions would be helpful for others who want to begin contributing to this project.

**Comment by championswimmer** [comment]
added a bounty to this, feel free to go ahead and create a readme properly with contributing section

**Comment by Nshul** [comment]
Sure. Thank You. I would work on it.
