### ISSUE TITLE
Bug:Error while adding claims

### ISSUE THREAD

**Issue by Dhroov7** [coding-blocks/boss#94]
![screen shot 2018-05-26 at 12 42 50 pm](https://user-images.githubusercontent.com/18377905/40573670-3aa926ba-60b4-11e8-98f7-76c5dffe275f.png)

**Comment by architkshk** [comment]
This is due to adding multiple claims for same issue or PR.

**Comment by VibhorCodecianGupta** [comment]
Done here, #107 Please review :)

**Comment by till-tomorrow** [comment]
Has this issue been fixed?
